import { v4 as uuidv4 } from 'uuid';
import { Policy, Violation, OverrideRecord, AuditLog } from '../../../shared/types';

// In-memory store
const policies: Policy[] = [
  {
    id: uuidv4(),
    name: 'Phishing Link Detection',
    description: 'Detects suspicious or phishing-like URLs',
    pattern: '(bit\\.ly|tinyurl|suspicious|phish|malware|hack)',
    riskLevel: 'high',
    decision: 'restrict',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Sensitive Data Sharing',
    description: 'Flags copy-paste of sensitive information',
    pattern: '(password|ssn|social security|credit card|cvv|secret|api.?key)',
    riskLevel: 'high',
    decision: 'restrict',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'External Email Warning',
    description: 'Warns when emailing external domains',
    pattern: '(@gmail\\.com|@yahoo\\.com|@hotmail\\.com|@outlook\\.com)',
    riskLevel: 'medium',
    decision: 'warn',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Unverified AI Output',
    description: 'Flags AI-generated content being shared without review',
    pattern: '(generated by ai|chatgpt|ai output|llm response)',
    riskLevel: 'medium',
    decision: 'warn',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Copy-Paste Guard — Confidential Data',
    description: 'Detects copying of confidential company information',
    pattern: '(confidential|internal only|do not share|proprietary|trade secret|not for distribution|company private|restricted|classified|internal use only)',
    riskLevel: 'high',
    decision: 'restrict',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Copy-Paste Guard — Financial Data',
    description: 'Detects copying of internal financial information',
    pattern: '(revenue|profit|loss|forecast|budget|salary|compensation|quarterly|annual report|earnings|financial projection|headcount|acquisition)',
    riskLevel: 'high',
    decision: 'restrict',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Copy-Paste Guard — Customer Data',
    description: 'Detects copying of customer PII or contracts',
    pattern: '(customer name|client name|contract|nda|non-disclosure|account number|customer id|personal data|date of birth|home address|phone number|social security)',
    riskLevel: 'high',
    decision: 'restrict',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Copy-Paste Guard — Credentials',
    description: 'Detects copying of passwords, API keys, or tokens',
    pattern: '(password|api.?key|secret.?key|access.?token|bearer|private.?key|db.?password|connection.?string|auth.?token|webhook.?secret)',
    riskLevel: 'high',
    decision: 'restrict',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Copy-Paste Guard — Internal Communications',
    description: 'Warns when copying internal emails or Slack messages externally',
    pattern: '(internal memo|all hands|off the record|between us|do not forward|slack message|teams message|internal discussion|not for press)',
    riskLevel: 'medium',
    decision: 'warn',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: uuidv4(),
    name: 'Email Defender — Suspicious Link',
    description: 'Detects dangerous or phishing links opened from emails',
    pattern: '(bit\\.ly|tinyurl\\.com|t\\.co|ow\\.ly|goo\\.gl|shorturl|click\\.here|verify.{0,20}account|confirm.{0,20}password|login.{0,20}secure|update.{0,20}billing|\\.xyz|\\.tk|\\.top|\\.pw|\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}|paypa1|g00gle|amaz0n|micros0ft)',
    riskLevel: 'high',
    decision: 'restrict',
    enabled: true,
    createdAt: new Date().toISOString(),
  },
];

const violations: Violation[] = [];
const overrides: OverrideRecord[] = [];
const auditLogs: AuditLog[] = [];

// Policies
export function getAllPolicies(): Policy[] {
  return policies;
}

export function getPolicyById(id: string): Policy | undefined {
  return policies.find((p) => p.id === id);
}

export function createPolicy(data: Omit<Policy, 'id' | 'createdAt'>): Policy {
  const policy: Policy = { ...data, id: uuidv4(), createdAt: new Date().toISOString() };
  policies.push(policy);
  return policy;
}

export function updatePolicy(id: string, data: Partial<Omit<Policy, 'id' | 'createdAt'>>): Policy | null {
  const idx = policies.findIndex((p) => p.id === id);
  if (idx === -1) return null;
  policies[idx] = { ...policies[idx], ...data };
  return policies[idx];
}

export function deletePolicy(id: string): boolean {
  const idx = policies.findIndex((p) => p.id === id);
  if (idx === -1) return false;
  policies.splice(idx, 1);
  return true;
}

// Violations
export function getAllViolations(): Violation[] {
  return violations;
}

export function getViolationById(id: string): Violation | undefined {
  return violations.find((v) => v.id === id);
}

export function createViolation(data: Omit<Violation, 'id' | 'createdAt' | 'overridden'>): Violation {
  const violation: Violation = {
    ...data,
    id: uuidv4(),
    overridden: false,
    createdAt: new Date().toISOString(),
  };
  violations.push(violation);
  return violation;
}

export function markViolationOverridden(id: string, justification: string): Violation | null {
  const idx = violations.findIndex((v) => v.id === id);
  if (idx === -1) return null;
  violations[idx] = {
    ...violations[idx],
    overridden: true,
    overrideJustification: justification,
    overriddenAt: new Date().toISOString(),
  };
  return violations[idx];
}

// Overrides
export function getAllOverrides(): OverrideRecord[] {
  return overrides;
}

export function createOverride(data: Omit<OverrideRecord, 'id' | 'createdAt'>): OverrideRecord {
  const record: OverrideRecord = { ...data, id: uuidv4(), createdAt: new Date().toISOString() };
  overrides.push(record);
  return record;
}

// Audit Logs
export function getAllAuditLogs(): AuditLog[] {
  return auditLogs;
}

export function createAuditLog(event: string, details: Record<string, unknown>, userId?: string): AuditLog {
  const log: AuditLog = {
    id: uuidv4(),
    event,
    details,
    userId,
    timestamp: new Date().toISOString(),
  };
  auditLogs.push(log);
  return log;
}
